"""
hmm_vol_regimes.py
==================
Point-in-time (PIT) volatility-regime diagnostics via a per-asset 3-state
Gaussian HMM.

WHAT THIS IS
------------
For each asset (a column of a daily price DataFrame -- stock, ETF, or a strategy
NAV series) this computes, at a set of calc dates, the *filtered* probability
that the asset's return process is in a Low / Medium / High volatility state.

It is a LATENT-STATE ESTIMATE, not an ex-post classifier: at each date t it asks
"given returns up to and including t, what is the probability today is being
generated by each of the 3 vol regimes?" Nothing after t ever enters the estimate
for t -> strictly PIT.

KEY DESIGN POINTS (all deliberate)
----------------------------------
* Emission: Gaussian HMM on daily log returns. States are ORDERED BY FITTED
  VARIANCE after every fit, so index 0=Low, 1=Med, 2=High *always* -- this makes
  the probabilities comparable across calc dates and across the 1y/3y/5y windows
  (raw HMM state indices are arbitrary up to relabeling; sorting by variance fixes
  the identity to the economic axis we care about).
* Filtered, not smoothed: parameters are fit (EM) on the trailing window, then a
  forward pass gives P(state_t | y_{1:t}); we report its LAST step. We never use
  the Viterbi path or the Baum-Welch smoothed posterior (those peek at the future).
* Per-asset independent models (QQQ's vol regimes != a single stock's).
* Calc dates: first trading day of each month + the last date in the frame.
* Three trailing windows 1y/3y/5y, reported side-by-side. Agreement across windows
  => robust regime; disagreement (e.g. 1y=High, 5y=Low) => a recent shift the long
  window hasn't absorbed yet -- a fast-vs-slow early-shift signal, not noise.
* Best-effort warm-up (option A): each window uses min(window, available) history.
  Early on, the three windows coincide and progressively diverge as history grows
  past 1y, 3y, 5y. Hard floor: an asset is skipped at a date with < 1y of returns.
* Determinism: fixed seed + multi-restart EM (best log-likelihood kept).
* Guards: per-fit min observations, variance floor, degenerate/failed fit -> NaN.

PRIMARY ENGINE: hmmlearn.GaussianHMM for the fit. The PIT-critical forward filter
is implemented explicitly here (not delegated to a library smoother) so it is
auditable.
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from hmmlearn.hmm import GaussianHMM


# ── Configuration ─────────────────────────────────────────────────────────────
TRADING_DAYS_PER_YEAR = 252
WINDOWS_YEARS         = (1, 3, 5)
N_STATES              = 3                       # Low / Med / High vol
STATE_LABELS          = ('Low', 'Med', 'High')  # index order == ascending variance
MIN_OBS_TO_FIT        = TRADING_DAYS_PER_YEAR    # hard floor: >= 1y of returns
VAR_FLOOR             = 1e-12                     # variance floor (degenerate guard)
# hmmlearn's GaussianHMM default min_covar=1e-3 is WRONG for daily returns: real
# daily-return variances are ~1e-4 (vol ~1.6%/day), so a 1e-3 covariance floor
# forces every state to >=~50% annualized vol and corrupts the fit (this was the
# main cause of the convergence-failure / NaN flood). Set it to daily-return scale.
MIN_COVAR             = 1e-8
# Degenerate-state guard: a fitted "state" with a runaway variance is EM filler,
# not a regime. Reject the fit if any state's annualized vol exceeds the ceiling.
# (Symptom previously seen in calm windows: vol_med = vol_high ~ 502 annualized.)
# NOTE: NO state-occupancy floor -- in a vol model the High state is SUPPOSED to be
# rarely occupied in calm periods; low occupancy is signal, not degeneracy.
VOL_ANN_CEILING       = 5.0                      # 500% annualized vol -> degenerate
EM_RESTARTS           = 12                       # multi-init; keep best VALID log-lik
EM_MAX_ITER           = 200
EM_TOL                = 1e-4
BASE_SEED             = 20260101                 # deterministic


# ── Result container ──────────────────────────────────────────────────────────
@dataclass
class RegimeRow:
    asset: str
    date: pd.Timestamp
    window_years: int
    n_obs: int                       # returns actually used in the fit
    p_low: float
    p_med: float
    p_high: float
    converged: bool
    # fitted per-state daily vol (annualized), in Low/Med/High order, for context
    vol_low: float
    vol_med: float
    vol_high: float


# ── Core: explicit Gaussian forward filter (PIT) ──────────────────────────────
def _gaussian_logpdf(x: np.ndarray, mean: float, var: float) -> np.ndarray:
    """Log N(x; mean, var) for a 1-D array x. var already variance-floored."""
    return -0.5 * (np.log(2.0 * np.pi * var) + (x - mean) ** 2 / var)


def forward_filter_last(returns: np.ndarray,
                        startprob: np.ndarray,
                        transmat: np.ndarray,
                        means: np.ndarray,
                        variances: np.ndarray) -> Optional[np.ndarray]:
    """
    Explicit, scaled forward pass. Returns the FILTERED state distribution at the
    LAST observation: P(state_T | returns_{1:T}). This is the PIT quantity --
    it conditions only on observations up to and including T.

    Parameters are the fitted HMM params (already ordered however the caller
    wants; this routine does not reorder). Scaling per step keeps it numerically
    stable and yields normalized filtered probabilities directly.

    Returns None if anything is degenerate (so callers emit NaN).
    """
    T = returns.shape[0]
    K = startprob.shape[0]
    if T == 0:
        return None

    var = np.maximum(variances, VAR_FLOOR)

    # Emission likelihoods per state per time (work in log, exponentiate per step).
    # alpha_t(i) ∝ P(state_t=i | y_{1:t}); we renormalize each step (scaling).
    alpha = np.zeros(K)

    # t = 0
    log_b0 = np.array([_gaussian_logpdf(returns[0:1], means[i], var[i])[0]
                       for i in range(K)])
    # combine with start prob in log, then exp-normalize
    with np.errstate(under='ignore'):
        log_a0 = np.log(np.maximum(startprob, 1e-300)) + log_b0
    a0 = np.exp(log_a0 - log_a0.max())
    s0 = a0.sum()
    if not np.isfinite(s0) or s0 <= 0:
        return None
    alpha = a0 / s0

    # t = 1..T-1
    for t in range(1, T):
        log_bt = np.array([_gaussian_logpdf(returns[t:t + 1], means[i], var[i])[0]
                           for i in range(K)])
        # predict: alpha_pred(j) = sum_i alpha(i) * transmat(i, j)
        pred = alpha @ transmat
        pred = np.maximum(pred, 1e-300)
        log_a = np.log(pred) + log_bt
        a = np.exp(log_a - log_a.max())
        s = a.sum()
        if not np.isfinite(s) or s <= 0:
            return None
        alpha = a / s

    return alpha   # filtered P(state_T | y_{1:T}), length K


# ── Fit one window: hmmlearn EM + multi-restart + variance ordering ───────────
def _fit_hmm_ordered(returns: np.ndarray, seed: int,
                     warm: Optional[Tuple[np.ndarray, np.ndarray,
                                          np.ndarray, np.ndarray]] = None
                     ) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray,
                                         np.ndarray, bool]]:
    """
    Fit a K-state Gaussian HMM on `returns` (1-D) with multi-restart EM, keep the
    best log-likelihood, then REORDER states by ascending variance so index
    0=Low,1=Med,2=High. Returns (startprob, transmat, means, variances, converged)
    with rows/entries permuted into variance order, or None on failure / degenerate.

    warm : optional (startprob, transmat, means, variances) from the PREVIOUS calc
        date's accepted fit (already variance-ordered). When supplied, one EM run is
        seeded from these parameters (warm-start) IN ADDITION to the cold restarts,
        and the best-log-likelihood fit across all of them is kept. Warm-starting
        makes the monthly parameter series temporally coherent (absent a real change
        the fit stays put) and helps thin/calm windows avoid collapsed states.

    A fit is REJECTED (-> None) if any state is degenerate: annualized vol above
    VOL_ANN_CEILING, or posterior occupancy below MIN_STATE_OCCUPANCY. Such a
    "state" is EM filler (no observations, runaway variance), not a regime, and
    must not be reported as a clean reading.
    """
    n = returns.shape[0]
    if n < MIN_OBS_TO_FIT:
        return None

    X = returns.reshape(-1, 1).astype(float)
    best = None
    best_ll = -np.inf

    def _is_valid(model) -> bool:
        """A fit is eligible only if all params are finite and no state has a
        runaway (degenerate-collapse) variance. Checking this DURING selection --
        rather than only on the final winner -- ensures a degenerate but
        high-likelihood fit cannot win the likelihood race and force the whole
        date to NaN while valid cold-restart fits are discarded."""
        try:
            mu = model.means_.ravel()
            va = np.maximum(model.covars_.ravel(), VAR_FLOOR)
            sp = model.startprob_; tm = model.transmat_
        except Exception:
            return False
        if not (np.all(np.isfinite(mu)) and np.all(np.isfinite(va))
                and np.all(np.isfinite(sp)) and np.all(np.isfinite(tm))):
            return False
        ann = np.sqrt(va) * np.sqrt(TRADING_DAYS_PER_YEAR)
        if np.any(ann > VOL_ANN_CEILING):
            return False
        return True

    def _consider(model):
        nonlocal best, best_ll
        if not _is_valid(model):
            return                      # degenerate fits never become `best`
        try:
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                ll = model.score(X)
        except Exception:
            return
        if np.isfinite(ll) and ll > best_ll:
            best_ll = ll
            best = model

    # Warm-start run (seeded from previous accepted fit), if provided.
    if warm is not None:
        try:
            wsp, wtm, wmu, wvar = warm
            wm = GaussianHMM(n_components=N_STATES, covariance_type='diag',
                             n_iter=EM_MAX_ITER, tol=EM_TOL, random_state=seed,
                             init_params='', min_covar=MIN_COVAR)   # supply all params, EM refines
            wm.startprob_ = np.clip(wsp, 1e-6, None); wm.startprob_ /= wm.startprob_.sum()
            wm.transmat_  = wtm.copy()
            wm.means_     = wmu.reshape(-1, 1).copy()
            wm.covars_    = np.maximum(wvar, VAR_FLOOR).reshape(-1, 1).copy()
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                wm.fit(X)
            _consider(wm)
        except Exception:
            pass

    # Cold multi-restart runs.
    for r in range(EM_RESTARTS):
        model = GaussianHMM(
            n_components=N_STATES,
            covariance_type='diag',
            n_iter=EM_MAX_ITER,
            tol=EM_TOL,
            random_state=seed + r,
            init_params='stmc',   # init start/trans/means/covars
            min_covar=MIN_COVAR,  # daily-return scale (default 1e-3 is far too large)
        )
        try:
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                model.fit(X)
        except Exception:
            continue
        _consider(model)

    if best is None:
        return None

    means = best.means_.ravel().astype(float)
    variances = best.covars_.ravel().astype(float)
    variances = np.maximum(variances, VAR_FLOOR)
    startprob = best.startprob_.astype(float)
    transmat = best.transmat_.astype(float)

    # Degenerate guard 1: any non-finite param -> reject.
    if not (np.all(np.isfinite(means)) and np.all(np.isfinite(variances))
            and np.all(np.isfinite(startprob)) and np.all(np.isfinite(transmat))):
        return None

    # Degenerate guard 2: runaway variance (annualized vol above ceiling) -> reject.
    # This alone catches the EM-collapse symptom (a "state" with no observations and
    # variance running off to a garbage value, e.g. vol ~ 502). We deliberately do
    # NOT add an occupancy floor: in a volatility model the High state is SUPPOSED
    # to be rarely occupied during calm periods (it may fire only a handful of days
    # per year), and rejecting fits for low High-state occupancy throws away correct
    # fits. Low occupancy is signal (calm regime), not degeneracy.
    ann_vol = np.sqrt(variances) * np.sqrt(TRADING_DAYS_PER_YEAR)
    if np.any(ann_vol > VOL_ANN_CEILING):
        return None

    # Order states by ascending variance (Low, Med, High).
    order = np.argsort(variances)
    means_o = means[order]
    var_o = variances[order]
    startprob_o = startprob[order]
    transmat_o = transmat[np.ix_(order, order)]
    row_sums = transmat_o.sum(axis=1, keepdims=True)
    row_sums = np.where(row_sums > 0, row_sums, 1.0)
    transmat_o = transmat_o / row_sums

    converged = bool(getattr(best.monitor_, 'converged', False))
    return startprob_o, transmat_o, means_o, var_o, converged


# ── Calc-date construction ────────────────────────────────────────────────────
def _calc_dates(index: pd.DatetimeIndex, start_date: pd.Timestamp
                ) -> pd.DatetimeIndex:
    """
    First trading day of each month at/after start_date, plus the last date in
    the frame. Trading days are taken from the price index itself (so holidays
    are handled automatically -- we never invent a date not in the data).
    """
    idx = index[index >= start_date]
    if len(idx) == 0:
        return pd.DatetimeIndex([])
    df = pd.DataFrame(index=idx)
    # first available trading day within each calendar month
    first_of_month = (df.groupby([idx.year, idx.month])
                        .apply(lambda g: g.index.min()))
    dates = pd.DatetimeIndex(sorted(set(first_of_month.values)))
    last = index[-1]
    if last not in dates:
        dates = dates.append(pd.DatetimeIndex([last])).sort_values()
    return dates


# ── Public API ────────────────────────────────────────────────────────────────
def compute_regime_probabilities(prices: pd.DataFrame,
                                  start_date,
                                  windows_years: Tuple[int, ...] = WINDOWS_YEARS,
                                  warm_start: bool = False,
                                  verbose: bool = True) -> pd.DataFrame:
    """
    Compute PIT filtered volatility-regime probabilities for every asset.

    Parameters
    ----------
    prices : DataFrame
        Daily prices, DatetimeIndex (ascending) x assets (columns). May contain
        NaNs (e.g. an asset that starts late / a NAV series); each asset uses only
        its own non-NaN history.
    start_date : str | Timestamp
        First date for which outputs are produced. End date is the last index date.
    windows_years : tuple of int
        Trailing windows in years (default 1, 3, 5).
    verbose : bool
        Print per-asset progress.

    Returns
    -------
    DataFrame (long/tidy), one row per (asset, calc_date, window_years):
        asset, date, window_years, n_obs, p_low, p_med, p_high, converged,
        vol_low, vol_med, vol_high   (annualized per-state vols, Low/Med/High)
    Filtered probabilities are PIT: P(state at `date` | returns up to `date`).
    Rows are emitted only where the window had >= 1y of returns; otherwise the
    asset is skipped at that date (best-effort warm-up, option A).
    """
    if not isinstance(prices.index, pd.DatetimeIndex):
        prices = prices.copy()
        prices.index = pd.to_datetime(prices.index)
    prices = prices.sort_index()
    start_date = pd.Timestamp(start_date)

    calc_dates = _calc_dates(prices.index, start_date)
    if len(calc_dates) == 0:
        if verbose:
            print(f"  No trading dates on/after {start_date.date()} -- nothing to do.")
        return _empty_frame()

    # log returns per asset (column-wise; NaNs preserved where price missing)
    log_px = np.log(prices.where(prices > 0))
    rets = log_px.diff()

    win_obs = {w: int(round(w * TRADING_DAYS_PER_YEAR)) for w in windows_years}
    max_win = max(win_obs.values())

    rows: List[RegimeRow] = []
    assets = list(prices.columns)

    for ai, asset in enumerate(assets):
        r_full = rets[asset].dropna()
        if r_full.empty:
            if verbose:
                print(f"  [{ai+1}/{len(assets)}] {asset}: no returns, skipped")
            continue

        # deterministic per-asset seed (stable across runs, varies by asset)
        a_seed = BASE_SEED + (abs(hash(asset)) % 100000)

        # Warm-start cache: last ACCEPTED (variance-ordered) params per window, so
        # each calc date's fit is seeded from the prior month's solution. Reset per
        # asset (a new asset has no prior trajectory). Only updated on a non-degenerate
        # fit, so a rejected/NaN month does not poison the next month's warm-start.
        warm_by_window: Dict[int, Tuple[np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray]] = {}

        n_emit = 0
        for dt in calc_dates:
            # returns strictly up to and including dt (PIT)
            r_upto = r_full.loc[:dt]
            avail = r_upto.shape[0]
            if avail < MIN_OBS_TO_FIT:
                continue   # < 1y available -> skip asset at this date (floor)

            for w in windows_years:
                w_obs = win_obs[w]
                # best-effort (option A): use min(window, available)
                use = r_upto.iloc[-min(w_obs, avail):].values
                if use.shape[0] < MIN_OBS_TO_FIT:
                    continue

                fit = _fit_hmm_ordered(use, seed=a_seed,
                                       warm=warm_by_window.get(w) if warm_start else None)
                if fit is None:
                    rows.append(RegimeRow(asset, dt, w, use.shape[0],
                                          np.nan, np.nan, np.nan, False,
                                          np.nan, np.nan, np.nan))
                    continue

                startprob, transmat, means, variances, converged = fit
                # update warm-start for this window from the accepted fit
                warm_by_window[w] = (startprob, transmat, means, variances)
                filt = forward_filter_last(use, startprob, transmat, means, variances)
                if filt is None:
                    rows.append(RegimeRow(asset, dt, w, use.shape[0],
                                          np.nan, np.nan, np.nan, False,
                                          np.nan, np.nan, np.nan))
                    continue

                ann = np.sqrt(variances) * np.sqrt(TRADING_DAYS_PER_YEAR)
                rows.append(RegimeRow(
                    asset, dt, w, use.shape[0],
                    float(filt[0]), float(filt[1]), float(filt[2]),
                    converged,
                    float(ann[0]), float(ann[1]), float(ann[2]),
                ))
                n_emit += 1

        if verbose:
            print(f"  [{ai+1}/{len(assets)}] {asset}: {n_emit} window-rows "
                  f"across {len(calc_dates)} calc dates")

    return _rows_to_frame(rows)


def _empty_frame() -> pd.DataFrame:
    cols = ['asset', 'date', 'window_years', 'n_obs', 'p_low', 'p_med', 'p_high',
            'converged', 'vol_low', 'vol_med', 'vol_high']
    return pd.DataFrame(columns=cols)


def _rows_to_frame(rows: List[RegimeRow]) -> pd.DataFrame:
    if not rows:
        return _empty_frame()
    df = pd.DataFrame([r.__dict__ for r in rows])
    return df.sort_values(['asset', 'date', 'window_years']).reset_index(drop=True)


# ── Convenience: wide view for one asset (windows side by side) ───────────────
def regime_wide(df: pd.DataFrame, asset: str) -> pd.DataFrame:
    """
    Pivot the tidy output for a single asset into a date-indexed wide view with
    the 1y/3y/5y windows side by side per state, so dispersion across windows is
    visible at a glance (agreement = robust regime; disagreement = recent shift).
    """
    sub = df[df['asset'] == asset]
    if sub.empty:
        return pd.DataFrame()
    wide = sub.pivot_table(index='date', columns='window_years',
                           values=['p_low', 'p_med', 'p_high'])
    # flatten column names: ('p_high', 3) -> 'p_high_3y'
    wide.columns = [f"{p}_{w}y" for (p, w) in wide.columns]
    return wide.sort_index()
