"""
hmm_vol_regimes.py
==================
Point-in-time (PIT) volatility-regime diagnostics via a per-asset 3-state
Gaussian HMM.

WHAT THIS IS
------------
For each asset (a column of a daily price DataFrame -- stock, ETF, or a strategy
NAV series) this computes, at a set of calc dates, the *filtered* probability
that the asset's return process is in a Low / Medium / High volatility state.

It is a LATENT-STATE ESTIMATE, not an ex-post classifier: at each date t it asks
"given returns up to and including t, what is the probability today is being
generated by each of the 3 vol regimes?" Nothing after t ever enters the estimate
for t -> strictly PIT.

KEY DESIGN POINTS (all deliberate)
----------------------------------
* Emission: Gaussian HMM on daily log returns. States are ORDERED BY FITTED
  VARIANCE after every fit, so index 0=Low, 1=Med, 2=High *always* -- this makes
  the probabilities comparable across calc dates and across the 1y/3y/5y windows
  (raw HMM state indices are arbitrary up to relabeling; sorting by variance fixes
  the identity to the economic axis we care about).
* Filtered, not smoothed: parameters are fit (EM) on the trailing window, then a
  forward pass gives P(state_t | y_{1:t}); we report its LAST step. We never use
  the Viterbi path or the Baum-Welch smoothed posterior (those peek at the future).
* Per-asset independent models (QQQ's vol regimes != a single stock's).
* Calc dates: first trading day of each month + the last date in the frame.
* Three trailing windows 1y/3y/5y, reported side-by-side. Agreement across windows
  => robust regime; disagreement (e.g. 1y=High, 5y=Low) => a recent shift the long
  window hasn't absorbed yet -- a fast-vs-slow early-shift signal, not noise.
* Best-effort warm-up (option A): each window uses min(window, available) history.
  Early on, the three windows coincide and progressively diverge as history grows
  past 1y, 3y, 5y. Hard floor: an asset is skipped at a date with < 1y of returns.
* Determinism: fixed seed + multi-restart EM (best log-likelihood kept).
* Guards: per-fit min observations, variance floor, degenerate/failed fit -> NaN.

PRIMARY ENGINE: hmmlearn.GaussianHMM for the fit. The PIT-critical forward filter
is implemented explicitly here (not delegated to a library smoother) so it is
auditable.

DAILY CACHE (lower section of this file): for the timeliness study the same
machinery is run at DAILY frequency and cached in Postgres via run_regime_cache(),
with incremental/rebuild modes, warm-start resume, and per-asset checkpointing.
The monthly compute_regime_probabilities() above remains for quick in-memory use.
"""

from __future__ import annotations

import json
import warnings
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from hmmlearn.hmm import GaussianHMM
from sqlalchemy import create_engine, text


# ── Configuration ─────────────────────────────────────────────────────────────
TRADING_DAYS_PER_YEAR = 252
WINDOWS_YEARS         = (1, 3, 5)
N_STATES              = 3                       # Low / Med / High vol
STATE_LABELS          = ('Low', 'Med', 'High')  # index order == ascending variance
MIN_OBS_TO_FIT        = TRADING_DAYS_PER_YEAR    # hard floor: >= 1y of returns
VAR_FLOOR             = 1e-12                     # variance floor (degenerate guard)
# hmmlearn's GaussianHMM default min_covar=1e-3 is WRONG for daily returns: real
# daily-return variances are ~1e-4 (vol ~1.6%/day), so a 1e-3 covariance floor
# forces every state to >=~50% annualized vol and corrupts the fit (this was the
# main cause of the convergence-failure / NaN flood). Set it to daily-return scale.
MIN_COVAR             = 1e-8
# Degenerate-state guard: a fitted "state" with a runaway variance is EM filler,
# not a regime. Reject the fit if any state's annualized vol exceeds the ceiling.
# (Symptom previously seen in calm windows: vol_med = vol_high ~ 502 annualized.)
# NOTE: NO state-occupancy floor -- in a vol model the High state is SUPPOSED to be
# rarely occupied in calm periods; low occupancy is signal, not degeneracy.
VOL_ANN_CEILING       = 5.0                      # 500% annualized vol -> degenerate
EM_RESTARTS           = 12                       # multi-init; keep best VALID log-lik
EM_MAX_ITER           = 200
EM_TOL                = 1e-4
BASE_SEED             = 20260101                 # deterministic


# ── Result container ──────────────────────────────────────────────────────────
@dataclass
class RegimeRow:
    asset: str
    date: pd.Timestamp
    window_years: int
    n_obs: int                       # returns actually used in the fit
    p_low: float
    p_med: float
    p_high: float
    converged: bool
    # fitted per-state daily vol (annualized), in Low/Med/High order, for context
    vol_low: float
    vol_med: float
    vol_high: float


# ── Core: explicit Gaussian forward filter (PIT) ──────────────────────────────
def _gaussian_logpdf(x: np.ndarray, mean: float, var: float) -> np.ndarray:
    """Log N(x; mean, var) for a 1-D array x. var already variance-floored."""
    return -0.5 * (np.log(2.0 * np.pi * var) + (x - mean) ** 2 / var)


def forward_filter_last(returns: np.ndarray,
                        startprob: np.ndarray,
                        transmat: np.ndarray,
                        means: np.ndarray,
                        variances: np.ndarray) -> Optional[np.ndarray]:
    """
    Explicit, scaled forward pass. Returns the FILTERED state distribution at the
    LAST observation: P(state_T | returns_{1:T}). This is the PIT quantity --
    it conditions only on observations up to and including T.

    Parameters are the fitted HMM params (already ordered however the caller
    wants; this routine does not reorder). Scaling per step keeps it numerically
    stable and yields normalized filtered probabilities directly.

    Returns None if anything is degenerate (so callers emit NaN).
    """
    T = returns.shape[0]
    K = startprob.shape[0]
    if T == 0:
        return None

    var = np.maximum(variances, VAR_FLOOR)

    # Emission likelihoods per state per time (work in log, exponentiate per step).
    # alpha_t(i) ∝ P(state_t=i | y_{1:t}); we renormalize each step (scaling).
    alpha = np.zeros(K)

    # t = 0
    log_b0 = np.array([_gaussian_logpdf(returns[0:1], means[i], var[i])[0]
                       for i in range(K)])
    # combine with start prob in log, then exp-normalize
    with np.errstate(under='ignore'):
        log_a0 = np.log(np.maximum(startprob, 1e-300)) + log_b0
    a0 = np.exp(log_a0 - log_a0.max())
    s0 = a0.sum()
    if not np.isfinite(s0) or s0 <= 0:
        return None
    alpha = a0 / s0

    # t = 1..T-1
    for t in range(1, T):
        log_bt = np.array([_gaussian_logpdf(returns[t:t + 1], means[i], var[i])[0]
                           for i in range(K)])
        # predict: alpha_pred(j) = sum_i alpha(i) * transmat(i, j)
        pred = alpha @ transmat
        pred = np.maximum(pred, 1e-300)
        log_a = np.log(pred) + log_bt
        a = np.exp(log_a - log_a.max())
        s = a.sum()
        if not np.isfinite(s) or s <= 0:
            return None
        alpha = a / s

    return alpha   # filtered P(state_T | y_{1:T}), length K


# ── Fit one window: hmmlearn EM + multi-restart + variance ordering ───────────
def _fit_hmm_ordered(returns: np.ndarray, seed: int,
                     warm: Optional[Tuple[np.ndarray, np.ndarray,
                                          np.ndarray, np.ndarray]] = None
                     ) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray,
                                         np.ndarray, bool]]:
    """
    Fit a K-state Gaussian HMM on `returns` (1-D) with multi-restart EM, keep the
    best log-likelihood, then REORDER states by ascending variance so index
    0=Low,1=Med,2=High. Returns (startprob, transmat, means, variances, converged)
    with rows/entries permuted into variance order, or None on failure / degenerate.

    warm : optional (startprob, transmat, means, variances) from the PREVIOUS calc
        date's accepted fit (already variance-ordered). When supplied, one EM run is
        seeded from these parameters (warm-start) IN ADDITION to the cold restarts,
        and the best-log-likelihood fit across all of them is kept. Warm-starting
        makes the monthly parameter series temporally coherent (absent a real change
        the fit stays put) and helps thin/calm windows avoid collapsed states.

    A fit is REJECTED (-> None) if any state is degenerate: annualized vol above
    VOL_ANN_CEILING, or posterior occupancy below MIN_STATE_OCCUPANCY. Such a
    "state" is EM filler (no observations, runaway variance), not a regime, and
    must not be reported as a clean reading.
    """
    n = returns.shape[0]
    if n < MIN_OBS_TO_FIT:
        return None

    X = returns.reshape(-1, 1).astype(float)
    best = None
    best_ll = -np.inf

    def _is_valid(model) -> bool:
        """A fit is eligible only if all params are finite and no state has a
        runaway (degenerate-collapse) variance. Checking this DURING selection --
        rather than only on the final winner -- ensures a degenerate but
        high-likelihood fit cannot win the likelihood race and force the whole
        date to NaN while valid cold-restart fits are discarded."""
        try:
            mu = model.means_.ravel()
            va = np.maximum(model.covars_.ravel(), VAR_FLOOR)
            sp = model.startprob_; tm = model.transmat_
        except Exception:
            return False
        if not (np.all(np.isfinite(mu)) and np.all(np.isfinite(va))
                and np.all(np.isfinite(sp)) and np.all(np.isfinite(tm))):
            return False
        ann = np.sqrt(va) * np.sqrt(TRADING_DAYS_PER_YEAR)
        if np.any(ann > VOL_ANN_CEILING):
            return False
        return True

    def _consider(model):
        nonlocal best, best_ll
        if not _is_valid(model):
            return                      # degenerate fits never become `best`
        try:
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                ll = model.score(X)
        except Exception:
            return
        if np.isfinite(ll) and ll > best_ll:
            best_ll = ll
            best = model

    # Warm-start run (seeded from previous accepted fit), if provided.
    if warm is not None:
        try:
            wsp, wtm, wmu, wvar = warm
            wm = GaussianHMM(n_components=N_STATES, covariance_type='diag',
                             n_iter=EM_MAX_ITER, tol=EM_TOL, random_state=seed,
                             init_params='', min_covar=MIN_COVAR)   # supply all params, EM refines
            wm.startprob_ = np.clip(wsp, 1e-6, None); wm.startprob_ /= wm.startprob_.sum()
            wm.transmat_  = wtm.copy()
            wm.means_     = wmu.reshape(-1, 1).copy()
            wm.covars_    = np.maximum(wvar, VAR_FLOOR).reshape(-1, 1).copy()
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                wm.fit(X)
            _consider(wm)
        except Exception:
            pass

    # Cold multi-restart runs.
    for r in range(EM_RESTARTS):
        model = GaussianHMM(
            n_components=N_STATES,
            covariance_type='diag',
            n_iter=EM_MAX_ITER,
            tol=EM_TOL,
            random_state=seed + r,
            init_params='stmc',   # init start/trans/means/covars
            min_covar=MIN_COVAR,  # daily-return scale (default 1e-3 is far too large)
        )
        try:
            with warnings.catch_warnings():
                warnings.simplefilter('ignore')
                model.fit(X)
        except Exception:
            continue
        _consider(model)

    if best is None:
        return None

    means = best.means_.ravel().astype(float)
    variances = best.covars_.ravel().astype(float)
    variances = np.maximum(variances, VAR_FLOOR)
    startprob = best.startprob_.astype(float)
    transmat = best.transmat_.astype(float)

    # Degenerate guard 1: any non-finite param -> reject.
    if not (np.all(np.isfinite(means)) and np.all(np.isfinite(variances))
            and np.all(np.isfinite(startprob)) and np.all(np.isfinite(transmat))):
        return None

    # Degenerate guard 2: runaway variance (annualized vol above ceiling) -> reject.
    # This alone catches the EM-collapse symptom (a "state" with no observations and
    # variance running off to a garbage value, e.g. vol ~ 502). We deliberately do
    # NOT add an occupancy floor: in a volatility model the High state is SUPPOSED
    # to be rarely occupied during calm periods (it may fire only a handful of days
    # per year), and rejecting fits for low High-state occupancy throws away correct
    # fits. Low occupancy is signal (calm regime), not degeneracy.
    ann_vol = np.sqrt(variances) * np.sqrt(TRADING_DAYS_PER_YEAR)
    if np.any(ann_vol > VOL_ANN_CEILING):
        return None

    # Order states by ascending variance (Low, Med, High).
    order = np.argsort(variances)
    means_o = means[order]
    var_o = variances[order]
    startprob_o = startprob[order]
    transmat_o = transmat[np.ix_(order, order)]
    row_sums = transmat_o.sum(axis=1, keepdims=True)
    row_sums = np.where(row_sums > 0, row_sums, 1.0)
    transmat_o = transmat_o / row_sums

    converged = bool(getattr(best.monitor_, 'converged', False))
    return startprob_o, transmat_o, means_o, var_o, converged


# ── Calc-date construction ────────────────────────────────────────────────────
def _calc_dates(index: pd.DatetimeIndex, start_date: pd.Timestamp,
                frequency: str = 'monthly') -> pd.DatetimeIndex:
    """
    Calc dates drawn from the price index itself (so holidays are handled
    automatically -- we never invent a date not in the data).

    frequency='monthly' : first trading day of each month + the last frame date.
    frequency='daily'    : every trading day on/after start_date (used for the
                           timeliness study, where signal lag matters to the day).
    """
    idx = index[index >= start_date]
    if len(idx) == 0:
        return pd.DatetimeIndex([])
    if frequency == 'daily':
        return pd.DatetimeIndex(idx)
    # monthly: first available trading day within each calendar month
    df = pd.DataFrame(index=idx)
    first_of_month = (df.groupby([idx.year, idx.month])
                        .apply(lambda g: g.index.min()))
    dates = pd.DatetimeIndex(sorted(set(first_of_month.values)))
    last = index[-1]
    if last not in dates:
        dates = dates.append(pd.DatetimeIndex([last])).sort_values()
    return dates


# ── Public API ────────────────────────────────────────────────────────────────
def compute_regime_probabilities(prices: pd.DataFrame,
                                  start_date,
                                  windows_years: Tuple[int, ...] = WINDOWS_YEARS,
                                  warm_start: bool = False,
                                  frequency: str = 'monthly',
                                  verbose: bool = True) -> pd.DataFrame:
    """
    Compute PIT filtered volatility-regime probabilities for every asset.

    Parameters
    ----------
    prices : DataFrame
        Daily prices, DatetimeIndex (ascending) x assets (columns). May contain
        NaNs (e.g. an asset that starts late / a NAV series); each asset uses only
        its own non-NaN history.
    start_date : str | Timestamp
        First date for which outputs are produced. End date is the last index date.
    windows_years : tuple of int
        Trailing windows in years (default 1, 3, 5).
    verbose : bool
        Print per-asset progress.

    Returns
    -------
    DataFrame (long/tidy), one row per (asset, calc_date, window_years):
        asset, date, window_years, n_obs, p_low, p_med, p_high, converged,
        vol_low, vol_med, vol_high   (annualized per-state vols, Low/Med/High)
    Filtered probabilities are PIT: P(state at `date` | returns up to `date`).
    Rows are emitted only where the window had >= 1y of returns; otherwise the
    asset is skipped at that date (best-effort warm-up, option A).
    """
    if not isinstance(prices.index, pd.DatetimeIndex):
        prices = prices.copy()
        prices.index = pd.to_datetime(prices.index)
    prices = prices.sort_index()
    start_date = pd.Timestamp(start_date)

    calc_dates = _calc_dates(prices.index, start_date, frequency=frequency)
    if len(calc_dates) == 0:
        if verbose:
            print(f"  No trading dates on/after {start_date.date()} -- nothing to do.")
        return _empty_frame()

    # log returns per asset (column-wise; NaNs preserved where price missing)
    log_px = np.log(prices.where(prices > 0))
    rets = log_px.diff()

    win_obs = {w: int(round(w * TRADING_DAYS_PER_YEAR)) for w in windows_years}
    max_win = max(win_obs.values())

    rows: List[RegimeRow] = []
    assets = list(prices.columns)

    for ai, asset in enumerate(assets):
        r_full = rets[asset].dropna()
        if r_full.empty:
            if verbose:
                print(f"  [{ai+1}/{len(assets)}] {asset}: no returns, skipped")
            continue

        # deterministic per-asset seed (stable across runs, varies by asset)
        a_seed = BASE_SEED + (abs(hash(asset)) % 100000)

        # Warm-start cache: last ACCEPTED (variance-ordered) params per window, so
        # each calc date's fit is seeded from the prior month's solution. Reset per
        # asset (a new asset has no prior trajectory). Only updated on a non-degenerate
        # fit, so a rejected/NaN month does not poison the next month's warm-start.
        warm_by_window: Dict[int, Tuple[np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray]] = {}

        n_emit = 0
        for dt in calc_dates:
            # returns strictly up to and including dt (PIT)
            r_upto = r_full.loc[:dt]
            avail = r_upto.shape[0]
            if avail < MIN_OBS_TO_FIT:
                continue   # < 1y available -> skip asset at this date (floor)

            for w in windows_years:
                w_obs = win_obs[w]
                # best-effort (option A): use min(window, available)
                use = r_upto.iloc[-min(w_obs, avail):].values
                if use.shape[0] < MIN_OBS_TO_FIT:
                    continue

                fit = _fit_hmm_ordered(use, seed=a_seed,
                                       warm=warm_by_window.get(w) if warm_start else None)
                if fit is None:
                    rows.append(RegimeRow(asset, dt, w, use.shape[0],
                                          np.nan, np.nan, np.nan, False,
                                          np.nan, np.nan, np.nan))
                    continue

                startprob, transmat, means, variances, converged = fit
                # update warm-start for this window from the accepted fit
                warm_by_window[w] = (startprob, transmat, means, variances)
                filt = forward_filter_last(use, startprob, transmat, means, variances)
                if filt is None:
                    rows.append(RegimeRow(asset, dt, w, use.shape[0],
                                          np.nan, np.nan, np.nan, False,
                                          np.nan, np.nan, np.nan))
                    continue

                ann = np.sqrt(variances) * np.sqrt(TRADING_DAYS_PER_YEAR)
                rows.append(RegimeRow(
                    asset, dt, w, use.shape[0],
                    float(filt[0]), float(filt[1]), float(filt[2]),
                    converged,
                    float(ann[0]), float(ann[1]), float(ann[2]),
                ))
                n_emit += 1

        if verbose:
            print(f"  [{ai+1}/{len(assets)}] {asset}: {n_emit} window-rows "
                  f"across {len(calc_dates)} calc dates")

    return _rows_to_frame(rows)


def _empty_frame() -> pd.DataFrame:
    cols = ['asset', 'date', 'window_years', 'n_obs', 'p_low', 'p_med', 'p_high',
            'converged', 'vol_low', 'vol_med', 'vol_high']
    return pd.DataFrame(columns=cols)


def _rows_to_frame(rows: List[RegimeRow]) -> pd.DataFrame:
    if not rows:
        return _empty_frame()
    df = pd.DataFrame([r.__dict__ for r in rows])
    return df.sort_values(['asset', 'date', 'window_years']).reset_index(drop=True)


# ── Convenience: wide view for one asset (windows side by side) ───────────────
def regime_wide(df: pd.DataFrame, asset: str) -> pd.DataFrame:
    """
    Pivot the tidy output for a single asset into a date-indexed wide view with
    the 1y/3y/5y windows side by side per state, so dispersion across windows is
    visible at a glance (agreement = robust regime; disagreement = recent shift).
    """
    sub = df[df['asset'] == asset]
    if sub.empty:
        return pd.DataFrame()
    wide = sub.pivot_table(index='date', columns='window_years',
                           values=['p_low', 'p_med', 'p_high'])
    # flatten column names: ('p_high', 3) -> 'p_high_3y'
    wide.columns = [f"{p}_{w}y" for (p, w) in wide.columns]
    return wide.sort_index()


# ══════════════════════════════════════════════════════════════════════════════
#  POSTGRES-BACKED DAILY CACHE (incremental / rebuild)
# ══════════════════════════════════════════════════════════════════════════════
#  Daily PIT regime probabilities cached in Postgres for the timeliness study.
#  Two tables: results (hmm_regime_cache) + warm-start state (hmm_warmstart_state).
#  Modes: 'rebuild' (drop+recompute per asset) | 'incremental' (resume; always
#  recompute the provisional last frame date). Per-asset checkpoint commits.
# ══════════════════════════════════════════════════════════════════════════════


# Model version: bump when the emission model / fit logic changes (e.g. Gaussian
# -> Student-t), so cached results from a different model are never silently mixed
# with new ones. Incremental runs require a matching model_version; a mismatch is
# treated as "no cache for this asset" (i.e. recompute), never a silent reuse.
MODEL_VERSION = 'gauss3_v1'

RESULTS_TBL   = 'hmm_regime_cache'
STATE_TBL     = 'hmm_warmstart_state'

DEFAULT_CONN  = 'postgresql+psycopg2://postgres:akf7a7j5@localhost:5432/factormodel_db'


# ── Schema ────────────────────────────────────────────────────────────────────
def ensure_tables(engine):
    with engine.begin() as conn:
        conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {RESULTS_TBL} (
                model_version VARCHAR(32) NOT NULL,
                asset         VARCHAR(64) NOT NULL,
                date          DATE        NOT NULL,
                window_years  INTEGER     NOT NULL,
                n_obs         INTEGER,
                p_low         DOUBLE PRECISION,
                p_med         DOUBLE PRECISION,
                p_high        DOUBLE PRECISION,
                converged     BOOLEAN,
                vol_low       DOUBLE PRECISION,
                vol_med       DOUBLE PRECISION,
                vol_high      DOUBLE PRECISION,
                PRIMARY KEY (model_version, asset, date, window_years)
            )
        """))
        conn.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {STATE_TBL} (
                model_version    VARCHAR(32) NOT NULL,
                asset            VARCHAR(64) NOT NULL,
                window_years     INTEGER     NOT NULL,
                params_asof_date DATE        NOT NULL,
                startprob_json   TEXT        NOT NULL,
                transmat_json    TEXT        NOT NULL,
                means_json       TEXT        NOT NULL,
                variances_json   TEXT        NOT NULL,
                PRIMARY KEY (model_version, asset, window_years)
            )
        """))


# ── Warm-start (de)serialization ──────────────────────────────────────────────
def _params_to_json(startprob, transmat, means, variances) -> Dict[str, str]:
    return {
        'startprob_json': json.dumps(np.asarray(startprob).tolist()),
        'transmat_json':  json.dumps(np.asarray(transmat).tolist()),
        'means_json':     json.dumps(np.asarray(means).tolist()),
        'variances_json': json.dumps(np.asarray(variances).tolist()),
    }


def _params_from_row(row) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    return (
        np.array(json.loads(row['startprob_json']), dtype=float),
        np.array(json.loads(row['transmat_json']),  dtype=float),
        np.array(json.loads(row['means_json']),     dtype=float),
        np.array(json.loads(row['variances_json']), dtype=float),
    )


# ── Cache reads ───────────────────────────────────────────────────────────────
def _last_cached_date(engine, asset: str) -> Optional[pd.Timestamp]:
    """Most recent RESULT date stored for this asset+model_version, or None."""
    with engine.connect() as conn:
        row = conn.execute(text(f"""
            SELECT MAX(date) FROM {RESULTS_TBL}
            WHERE model_version = :mv AND asset = :a
        """), {'mv': MODEL_VERSION, 'a': asset}).fetchone()
    return pd.Timestamp(row[0]) if row and row[0] is not None else None


def _load_warmstart(engine, asset: str
                    ) -> Dict[int, Tuple[pd.Timestamp, Tuple]]:
    """
    Load warm-start state for all windows of this asset.
    Returns {window_years: (params_asof_date, (startprob, transmat, means, var))}.
    """
    with engine.connect() as conn:
        rows = conn.execute(text(f"""
            SELECT window_years, params_asof_date, startprob_json, transmat_json,
                   means_json, variances_json
            FROM {STATE_TBL}
            WHERE model_version = :mv AND asset = :a
        """), {'mv': MODEL_VERSION, 'a': asset}).mappings().all()
    out = {}
    for r in rows:
        out[int(r['window_years'])] = (pd.Timestamp(r['params_asof_date']),
                                       _params_from_row(r))
    return out


# ── Cache writes (per-asset checkpoint) ───────────────────────────────────────
def _write_results(conn, model_version: str, result_rows: List[dict]):
    if not result_rows:
        return
    conn.execute(text(f"""
        INSERT INTO {RESULTS_TBL}
            (model_version, asset, date, window_years, n_obs,
             p_low, p_med, p_high, converged, vol_low, vol_med, vol_high)
        VALUES
            (:model_version, :asset, :date, :window_years, :n_obs,
             :p_low, :p_med, :p_high, :converged, :vol_low, :vol_med, :vol_high)
        ON CONFLICT (model_version, asset, date, window_years) DO UPDATE SET
            n_obs=EXCLUDED.n_obs, p_low=EXCLUDED.p_low, p_med=EXCLUDED.p_med,
            p_high=EXCLUDED.p_high, converged=EXCLUDED.converged,
            vol_low=EXCLUDED.vol_low, vol_med=EXCLUDED.vol_med,
            vol_high=EXCLUDED.vol_high
    """), result_rows)


def _write_warmstart(conn, model_version: str, asset: str, window: int,
                     asof: pd.Timestamp, params):
    startprob, transmat, means, variances = params
    payload = {'model_version': model_version, 'asset': asset,
               'window_years': window,
               'params_asof_date': pd.Timestamp(asof).strftime('%Y-%m-%d')}
    payload.update(_params_to_json(startprob, transmat, means, variances))
    conn.execute(text(f"""
        INSERT INTO {STATE_TBL}
            (model_version, asset, window_years, params_asof_date,
             startprob_json, transmat_json, means_json, variances_json)
        VALUES
            (:model_version, :asset, :window_years, :params_asof_date,
             :startprob_json, :transmat_json, :means_json, :variances_json)
        ON CONFLICT (model_version, asset, window_years) DO UPDATE SET
            params_asof_date=EXCLUDED.params_asof_date,
            startprob_json=EXCLUDED.startprob_json,
            transmat_json=EXCLUDED.transmat_json,
            means_json=EXCLUDED.means_json,
            variances_json=EXCLUDED.variances_json
    """), payload)


def _drop_asset(conn, model_version: str, asset: str):
    conn.execute(text(f"DELETE FROM {RESULTS_TBL} "
                      f"WHERE model_version=:mv AND asset=:a"),
                 {'mv': model_version, 'a': asset})
    conn.execute(text(f"DELETE FROM {STATE_TBL} "
                      f"WHERE model_version=:mv AND asset=:a"),
                 {'mv': model_version, 'a': asset})


# ── Per-asset compute over a set of calc dates (with warm-start chaining) ──────
def _compute_asset_dates(asset: str,
                         r_full: pd.Series,
                         calc_dates: pd.DatetimeIndex,
                         frame_last: pd.Timestamp,
                         windows_years: Tuple[int, ...],
                         seed: int,
                         warm_seed: Dict[int, Tuple],
                         verbose: bool = False,
                         progress_every: int = 250) -> Tuple[List[dict], Dict[int, Tuple[pd.Timestamp, Tuple]]]:
    """
    Compute every date in `calc_dates` (ascending) for one asset, chaining the
    warm-start day-by-day per window. Returns:
      result_rows : list of dicts for hmm_regime_cache
      new_state   : {window: (asof_date, params)} for FINALIZED dates only
                    (dates strictly before frame_last). The provisional last frame
                    date never advances state.

    warm_seed : {window: (startprob, transmat, means, variances)} initial seeds
                (from cached state on resume, or empty for a cold start).
    """
    win_obs = {w: int(round(w * TRADING_DAYS_PER_YEAR)) for w in windows_years}
    warm_by_window: Dict[int, Tuple] = dict(warm_seed)  # window -> params
    new_state: Dict[int, Tuple[pd.Timestamp, Tuple]] = {}
    result_rows: List[dict] = []
    _n_cd = len(calc_dates)

    for _di, dt in enumerate(calc_dates):
        if verbose and (_di % progress_every == 0):
            print(f"    [fit] {asset} {pd.Timestamp(dt).date()} "
                  f"({_di}/{_n_cd})", flush=True)
        r_upto = r_full.loc[:dt]
        avail = r_upto.shape[0]
        if avail < MIN_OBS_TO_FIT:
            continue   # < 1y -> skip asset at this date (floor)
        is_final = dt < frame_last   # finalized (not the provisional last frame day)

        for w in windows_years:
            w_obs = win_obs[w]
            use = r_upto.iloc[-min(w_obs, avail):].values
            if use.shape[0] < MIN_OBS_TO_FIT:
                continue

            fit = _fit_hmm_ordered(use, seed=seed, warm=warm_by_window.get(w))
            if fit is None:
                result_rows.append(_nan_row(asset, dt, w, int(use.shape[0])))
                continue

            startprob, transmat, means, variances, converged = fit
            params = (startprob, transmat, means, variances)
            # advance the in-run warm-start chain (used to seed the next day)
            warm_by_window[w] = params
            # only FINALIZED dates may become persisted warm-start state
            if is_final:
                new_state[w] = (dt, params)

            filt = forward_filter_last(use, startprob, transmat, means, variances)
            if filt is None:
                result_rows.append(_nan_row(asset, dt, w, int(use.shape[0])))
                continue

            ann = np.sqrt(variances) * np.sqrt(TRADING_DAYS_PER_YEAR)
            result_rows.append({
                'model_version': MODEL_VERSION, 'asset': asset,
                'date': pd.Timestamp(dt).strftime('%Y-%m-%d'),
                'window_years': int(w), 'n_obs': int(use.shape[0]),
                'p_low': float(filt[0]), 'p_med': float(filt[1]),
                'p_high': float(filt[2]), 'converged': bool(converged),
                'vol_low': float(ann[0]), 'vol_med': float(ann[1]),
                'vol_high': float(ann[2]),
            })

    return result_rows, new_state


def _nan_row(asset, dt, w, n_obs) -> dict:
    return {'model_version': MODEL_VERSION, 'asset': asset,
            'date': pd.Timestamp(dt).strftime('%Y-%m-%d'),
            'window_years': int(w), 'n_obs': int(n_obs),
            'p_low': None, 'p_med': None, 'p_high': None, 'converged': False,
            'vol_low': None, 'vol_med': None, 'vol_high': None}


# ── Public orchestrator ───────────────────────────────────────────────────────
def run_regime_cache(prices: pd.DataFrame,
                     start_date,
                     mode: str = 'incremental',
                     windows_years: Tuple[int, ...] = WINDOWS_YEARS,
                     conn_str: str = DEFAULT_CONN,
                     engine=None,
                     verbose: bool = True,
                     progress_every: int = 250) -> None:
    """
    Compute & cache DAILY PIT regime probabilities for every asset in `prices`.

    mode='rebuild'     : drop & recompute each asset's full daily history.
    mode='incremental' : resume each asset from its last cached date; always
                         recompute the (provisional) last frame date.

    Results land in Postgres (hmm_regime_cache); warm-start state in
    hmm_warmstart_state. Commits are per-asset (crash-safe for long runs).
    Use load_results(...) afterwards to pull the tidy frame back.
    """
    if mode not in ('incremental', 'rebuild'):
        raise ValueError("mode must be 'incremental' or 'rebuild'")
    if engine is None:
        engine = create_engine(conn_str)
    ensure_tables(engine)

    if not isinstance(prices.index, pd.DatetimeIndex):
        prices = prices.copy(); prices.index = pd.to_datetime(prices.index)
    prices = prices.sort_index()
    start_date = pd.Timestamp(start_date)
    frame_last = prices.index[-1]

    log_px = np.log(prices.where(prices > 0))
    rets = log_px.diff()
    assets = list(prices.columns)

    for ai, asset in enumerate(assets):
        r_full = rets[asset].dropna()
        if r_full.empty:
            if verbose:
                print(f"  [{ai+1}/{len(assets)}] {asset}: no returns, skipped")
            continue

        seed = BASE_SEED + (abs(hash(asset)) % 100000)

        # ── Determine this asset's calc window + warm-start seed by mode ──────
        if mode == 'rebuild':
            with engine.begin() as conn:
                _drop_asset(conn, MODEL_VERSION, asset)
            asset_start = start_date
            warm_seed = {}                       # cold start
        else:  # incremental
            last_cached = _last_cached_date(engine, asset)
            if last_cached is None:
                asset_start = start_date         # never cached -> full compute
                warm_seed = {}
            else:
                ws = _load_warmstart(engine, asset)
                # Resume from the day AFTER the last finalized warm-start date, but
                # never earlier than (last_cached). Because the previous run left the
                # last frame date provisional, recompute from min(params_asof+1day,
                # last_cached) forward. In practice: start at the earliest date whose
                # result is not yet finalized.
                if ws:
                    asof_dates = [v[0] for v in ws.values()]
                    resume_after = min(asof_dates)   # last finalized across windows
                else:
                    resume_after = last_cached       # no state -> redo last day
                # compute (resume_after, frame_last]  -- always includes frame_last
                asset_start = resume_after + pd.Timedelta(days=1)
                warm_seed = {w: v[1] for w, v in ws.items()}

        # calc dates = this asset's trading days in [asset_start, frame_last]
        idx = prices.index[(prices.index >= asset_start) &
                           (prices.index <= frame_last)]
        # ALWAYS include frame_last (provisional refresh), even if asset_start>last
        if frame_last not in idx:
            idx = idx.append(pd.DatetimeIndex([frame_last])).sort_values()
        calc_dates = pd.DatetimeIndex(idx)

        if len(calc_dates) == 0:
            if verbose:
                print(f"  [{ai+1}/{len(assets)}] {asset}: nothing to compute")
            continue

        result_rows, new_state = _compute_asset_dates(
            asset, r_full, calc_dates, frame_last, windows_years, seed, warm_seed,
            verbose=verbose, progress_every=progress_every)

        # ── Per-asset checkpoint commit (results + advanced state) ────────────
        with engine.begin() as conn:
            _write_results(conn, MODEL_VERSION, result_rows)
            for w, (asof, params) in new_state.items():
                _write_warmstart(conn, MODEL_VERSION, asset, w, asof, params)

        if verbose:
            n_final = len(new_state)
            print(f"  [{ai+1}/{len(assets)}] {asset}: {len(result_rows)} rows "
                  f"({mode}), {calc_dates[0].date()}..{calc_dates[-1].date()}, "
                  f"state advanced for {n_final} window(s)")


# ── Read back ─────────────────────────────────────────────────────────────────
def load_results(assets=None, conn_str: str = DEFAULT_CONN, engine=None,
                 model_version: str = MODEL_VERSION) -> pd.DataFrame:
    """Pull cached results into a tidy DataFrame (optionally filtered to assets)."""
    if engine is None:
        engine = create_engine(conn_str)
    q = f"""SELECT asset, date, window_years, n_obs, p_low, p_med, p_high,
                   converged, vol_low, vol_med, vol_high
            FROM {RESULTS_TBL} WHERE model_version = :mv"""
    params = {'mv': model_version}
    if assets is not None:
        q += " AND asset = ANY(:assets)"
        params['assets'] = list(assets)
    q += " ORDER BY asset, date, window_years"
    df = pd.read_sql(text(q), engine, params=params, parse_dates=['date'])
    return df


# ══════════════════════════════════════════════════════════════════════════════
#  VOLATILITY-QUINTILE INDICES (cross-sectional, PIT) + INTEGRATED ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════
#  Build synthetic Q1 (lowest-vol) and Q5 (highest-vol) index level series from a
#  universe of stock prices, then feed them to the same HMM regime cache. The idea
#  (idea 2): the high-vol slice of the market is where most risk/return sits, so its
#  vol-regime should shift earlier than the broad market; Q1 is the low-vol
#  reference, and the Q1-vs-Q5 contrast is itself informative.
#
#  PIT / construction rules (all deliberate):
#   * EWMA vol: log returns, trailing 252-day window, 21-day halflife.
#   * Eligibility on day t: a FULL 252-day trailing window AND no run of >5
#     consecutive identical (forward-filled) prices anywhere in that window.
#     (No separate min-history floor: the full-window requirement already excludes
#     recent IPOs -- which would otherwise inflate Q5 -- and the staleness rule
#     excludes halted/illiquid names whose carried prices understate their vol.)
#   * Daily cross-sectional quintiles (equal count) on EWMA vol; Q1=low, Q5=high.
#   * Index return for day t uses membership ranked on vol through t-1 (LAGGED ->
#     PIT), equal-weight average of those members' day-t returns.
#   * Skip a day with < MIN_QUANT_UNIVERSE eligible names.
#   * Levels compound from 1.0; frozen for days < last; incremental resumes the
#     compounding from the last frozen level (same discipline as named assets).

EWMA_VOL_WINDOW   = 252      # trailing window for EWMA vol
EWMA_VOL_HALFLIFE = 21       # responsiveness
STALE_MAX_RUN     = 5        # > this many identical consecutive prices -> ineligible
MIN_QUANT_UNIVERSE = 100     # min eligible names to form quintiles on a day
QUANT_INDEX_TBL   = 'hmm_quintile_index'   # cached synthetic index levels


def _ewma_vol_last(logret_window: np.ndarray) -> float:
    """EWMA volatility (std) of a 1-D log-return window, halflife EWMA_VOL_HALFLIFE.
    Returns the EWMA std as-of the LAST point of the window (the day t estimate)."""
    n = logret_window.shape[0]
    if n < EWMA_VOL_WINDOW:
        return np.nan
    lam = np.exp(np.log(0.5) / EWMA_VOL_HALFLIFE)
    # weights: most recent gets highest weight
    w = lam ** np.arange(n - 1, -1, -1)
    w = w / w.sum()
    mu = np.sum(w * logret_window)
    var = np.sum(w * (logret_window - mu) ** 2)
    return float(np.sqrt(var)) if np.isfinite(var) and var >= 0 else np.nan


def _max_identical_run(arr: np.ndarray) -> int:
    """Longest run of consecutive identical values in a 1-D array."""
    if arr.shape[0] == 0:
        return 0
    # run boundaries where value changes
    changes = np.concatenate(([True], arr[1:] != arr[:-1]))
    run_ids = np.cumsum(changes)
    # length of each run
    _, counts = np.unique(run_ids, return_counts=True)
    return int(counts.max())


def build_quintile_indices(prices: pd.DataFrame,
                           prefix: str,
                           start_date,
                           verbose: bool = True,
                           progress_every: int = 250
                           ) -> pd.DataFrame:
    """
    Construct PIT Q1 (low-vol) and Q5 (high-vol) equal-weight index LEVEL series
    from a universe of stock prices.

    Returns a DataFrame indexed by date with two columns: '{prefix}_VOLQ1' and
    '{prefix}_VOLQ5' (level series starting at 1.0). These are the synthetic
    "assets" to feed into run_regime_cache().

    Construction is strictly PIT: membership for day t is ranked on EWMA vol through
    t-1, applied to day-t returns.
    """
    if not isinstance(prices.index, pd.DatetimeIndex):
        prices = prices.copy(); prices.index = pd.to_datetime(prices.index)
    prices = prices.sort_index()
    start_date = pd.Timestamp(start_date)

    # Forward-fill, then work with log prices/returns.
    px = prices.ffill()
    logret = np.log(px).diff()

    dates = px.index
    tickers = list(px.columns)
    px_vals = px.values            # (T, N)
    lr_vals = logret.values        # (T, N)
    date_pos = {d: i for i, d in enumerate(dates)}

    # Output accumulators
    out_dates = []
    q1_ret = []      # equal-weight return of the LOW-vol quintile on each day
    q5_ret = []      # equal-weight return of the HIGH-vol quintile on each day

    # We need, for each day t: eligibility + EWMA vol computed on the window
    # ending at t-1 (to rank for day t). So we precompute, for each day d, the
    # set of eligible tickers and their EWMA vol AS OF d. Then membership for the
    # return on day t uses the ranking as of t-1.

    W = EWMA_VOL_WINDOW

    # Precompute per-day eligible vols (vol as-of day d, using window [d-W+1, d]).
    # Store as dict day_index -> {col_index: ewma_vol}.
    # We only need vols from ONE trading day BEFORE start_date onward: the first
    # index day (>= start_date) ranks on the prior day's vols, so the earliest vol
    # we ever consult is the last trading day before start_date. Computing vols for
    # the full pre-start_date history would be wasted work (the 252-day window still
    # reaches back in price space for each evaluated day; we just don't evaluate the
    # discarded early dates).
    pos = np.searchsorted(dates.values, np.datetime64(start_date), side='left')
    eval_from = max(W, pos - 1)        # one day before first index day (>= W)
    vol_asof: Dict[int, Dict[int, float]] = {}
    first_eval = None
    _n_dates = len(dates)
    for ti in range(eval_from, _n_dates):
        if verbose and (ti % progress_every == 0):
            print(f"  [quintile] vol precompute {dates[ti].date()} "
                  f"({ti - eval_from}/{_n_dates - eval_from})", flush=True)
        win_lo = ti - W + 1
        elig = {}
        for ci in range(len(tickers)):
            price_win = px_vals[win_lo:ti + 1, ci]
            ret_win = lr_vals[win_lo:ti + 1, ci]
            if np.any(~np.isfinite(price_win)):
                continue           # incomplete history (e.g. pre-IPO NaNs) -> skip
            # staleness: >STALE_MAX_RUN identical consecutive (ffill'd) prices
            if _max_identical_run(price_win) > STALE_MAX_RUN:
                continue
            # EWMA vol on the return window (ret_win has W entries; first may be NaN
            # if the very first price had no prior -- guard)
            rw = ret_win[np.isfinite(ret_win)]
            if rw.shape[0] < W - 1:
                continue
            v = _ewma_vol_last(rw[-W:] if rw.shape[0] >= W else rw)
            if np.isfinite(v) and v > 0:
                elig[ci] = v
        if len(elig) >= MIN_QUANT_UNIVERSE:
            vol_asof[ti] = elig
            if first_eval is None:
                first_eval = ti

    # Build daily index returns from start_date forward, ranking on t-1.
    for ti in range(len(dates)):
        d = dates[ti]
        if d < start_date:
            continue
        prev = ti - 1
        if prev not in vol_asof:
            continue               # no ranking available as of yesterday -> skip day
        elig = vol_asof[prev]
        # equal-count quintiles on yesterday's eligible vols
        cols = np.array(list(elig.keys()))
        vols = np.array([elig[c] for c in cols])
        if cols.shape[0] < MIN_QUANT_UNIVERSE:
            continue
        # quintile thresholds (equal count)
        ranks = pd.qcut(vols, 5, labels=False, duplicates='drop')
        # 'duplicates=drop' may yield <5 bins if many ties; require both ends present
        if ranks is None or np.nanmax(ranks) < 1:
            continue
        lo_q = np.nanmin(ranks)
        hi_q = np.nanmax(ranks)
        q1_cols = cols[ranks == lo_q]
        q5_cols = cols[ranks == hi_q]
        # day-t returns of those members (equal weight among present/valid)
        rt = lr_vals[ti, :]
        def _ew_ret(members):
            vals = rt[members]
            vals = vals[np.isfinite(vals)]
            return float(np.mean(vals)) if vals.shape[0] > 0 else np.nan
        r1 = _ew_ret(q1_cols)
        r5 = _ew_ret(q5_cols)
        if not (np.isfinite(r1) and np.isfinite(r5)):
            continue
        out_dates.append(d)
        q1_ret.append(r1)
        q5_ret.append(r5)

    if not out_dates:
        if verbose:
            print(f"  [quintile] no eligible days for prefix '{prefix}' "
                  f"(need >= {MIN_QUANT_UNIVERSE} eligible names/day)")
        return pd.DataFrame()

    idx = pd.DatetimeIndex(out_dates)
    # compound log returns into LEVEL series starting at 1.0
    lvl1 = np.exp(np.cumsum(q1_ret))
    lvl5 = np.exp(np.cumsum(q5_ret))
    out = pd.DataFrame({f"{prefix}_VOLQ1": lvl1, f"{prefix}_VOLQ5": lvl5}, index=idx)

    if verbose:
        print(f"  [quintile] prefix '{prefix}': built {len(out)} days "
              f"({idx[0].date()}..{idx[-1].date()}), "
              f"Q1 final={lvl1[-1]:.2f}x  Q5 final={lvl5[-1]:.2f}x")
    return out


def run_regime_analysis(prices: pd.DataFrame,
                        start_date,
                        mode: str = 'incremental',
                        conn_str: str = DEFAULT_CONN,
                        engine=None,
                        verbose: bool = True,
                        # non-interactive overrides (skip prompts when supplied):
                        analysis: Optional[str] = None,   # 'individual' | 'quantization'
                        prefix: Optional[str] = None
                        ) -> Optional[pd.DataFrame]:
    """
    Integrated entry point.

    If the universe has fewer than MIN_QUANT_UNIVERSE columns -> individual mode
    only (per-asset HMM regime cache).

    If it has >= MIN_QUANT_UNIVERSE columns -> prompt for:
        - analysis: 'individual'  (per-asset cache, the named-asset workflow), or
                    'quantization' (build {prefix}_VOLQ1/_VOLQ5 and cache those).
        - prefix (quantization only): names/namespaces the two series so the same
          machinery can run on multiple universes (e.g. 'SPX', 'R3000'). Re-running
          a prefix overwrites per the chosen mode (rebuild = full, incremental =
          extend from last cached day).

    Returns the quintile index level frame (quantization) or None (individual).
    Prompts can be bypassed by passing analysis= and prefix= explicitly.
    """
    if engine is None:
        engine = create_engine(conn_str)

    n_assets = prices.shape[1]
    if n_assets < MIN_QUANT_UNIVERSE:
        if verbose:
            print(f"  Universe has {n_assets} asset(s) (< {MIN_QUANT_UNIVERSE}); "
                  f"running INDIVIDUAL per-asset regime cache.")
        run_regime_cache(prices, start_date, mode=mode, conn_str=conn_str,
                         engine=engine, verbose=verbose)
        return None

    # >= MIN_QUANT_UNIVERSE: choose analysis type
    if analysis is None:
        analysis = input(
            f"Universe has {n_assets} assets. Choose analysis:\n"
            f"  [i] individual per-asset regime probabilities\n"
            f"  [q] quantization (build low/high vol-quintile indices)\n"
            f"Select (i/q): ").strip().lower()
        analysis = 'quantization' if analysis.startswith('q') else 'individual'

    if analysis == 'individual':
        run_regime_cache(prices, start_date, mode=mode, conn_str=conn_str,
                         engine=engine, verbose=verbose)
        return None

    # ── Quantization ──────────────────────────────────────────────────────────
    if prefix is None:
        prefix = input("Prefix for the two quintile series (e.g. SPX, R3000): ").strip()
    if not prefix:
        raise ValueError("A non-empty prefix is required for quantization mode.")

    # Mode prompt (rebuild vs incremental) if a cached prefix already exists.
    existing = _last_cached_date(engine, f"{prefix}_VOLQ5")
    if existing is not None and mode == 'incremental':
        # already what we want; honor it. (No guardrail on universe change -- the
        # user owns that discipline: change the universe => run mode='rebuild'.)
        if verbose:
            print(f"  Prefix '{prefix}' already cached up to {existing.date()}; "
                  f"incremental extend.")

    qidx = build_quintile_indices(prices, prefix, start_date, verbose=verbose)
    if qidx.empty:
        return qidx

    # Feed the two synthetic level series into the same HMM regime cache.
    run_regime_cache(qidx, start_date, mode=mode, conn_str=conn_str,
                     engine=engine, verbose=verbose)
    return qidx
